version: "3.9"
services:
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=maistodos-creditcard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  web:
    build: .
    command: python /src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/src
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
