# Generated by Django 4.2.4 on 2023-09-04 02:23

import creditcards.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creditcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holder",
                    models.CharField(
                        max_length=255,
                        validators=[creditcards.validators.validate_holder],
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[creditcards.validators.validate_number],
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                (
                    "exp_date",
                    models.CharField(
                        max_length=10,
                        validators=[creditcards.validators.validate_exp_date],
                    ),
                ),
                (
                    "cvv",
                    models.CharField(
                        max_length=4, validators=[creditcards.validators.validate_cvv]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
