# Generated by Django 4.2.4 on 2023-09-04 08:11

import creditcards.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creditcards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="number",
            field=models.CharField(
                max_length=255, validators=[creditcards.validators.validate_number]
            ),
        ),
    ]
